name: Auto Update Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    
    # Only run for releases (branches with format by_release*)
    if: |
      (github.event_name == 'push' && 
       contains(github.event.head_commit.message, 'Merge pull request') &&
       (contains(github.event.head_commit.message, 'by_release') || 
        contains(github.event.head_commit.message, 'by_release_v'))) ||
      (github.event_name == 'pull_request' && 
       github.event.pull_request.merged == true &&
       (startsWith(github.event.pull_request.head.ref, 'by_release') ||
        startsWith(github.event.pull_request.head.ref, 'by_release_v')))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Generate Enhanced Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "❌ package.json not found"